# Copyright (C) 2018 darktohka

PRODUCT_COPY_FILES += \
  vendor/actions/gs702a/proprietary/lib/libion.so:system/lib/libion.so \
  vendor/actions/gs702a/proprietary/lib/apMP3.so:system/lib/apMP3.so \
  vendor/actions/gs702a/proprietary/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
  vendor/actions/gs702a/proprietary/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
  vendor/actions/gs702a/proprietary/lib/avd_wmv.so:system/lib/avd_wmv.so \
  vendor/actions/gs702a/proprietary/lib/libgoogle_recognizer_jni.so:system/lib/libgoogle_recognizer_jni.so \
  vendor/actions/gs702a/proprietary/lib/libEGL.so:system/lib/libEGL.so \
  vendor/actions/gs702a/proprietary/lib/avd_mp4.so:system/lib/avd_mp4.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Video.Encoder.so:system/lib/libOMX.Action.Video.Encoder.so \
  vendor/actions/gs702a/proprietary/lib/vd_msm4.so:system/lib/vd_msm4.so \
  vendor/actions/gs702a/proprietary/lib/apAC3.so:system/lib/apAC3.so \
  vendor/actions/gs702a/proprietary/lib/apOGG.so:system/lib/apOGG.so \
  vendor/actions/gs702a/proprietary/lib/adMP3.so:system/lib/adMP3.so \
  vendor/actions/gs702a/proprietary/lib/vd_vp8.so:system/lib/vd_vp8.so \
  vendor/actions/gs702a/proprietary/lib/apWAV.so:system/lib/apWAV.so \
  vendor/actions/gs702a/proprietary/lib/adCOOK.so:system/lib/adCOOK.so \
  vendor/actions/gs702a/proprietary/lib/libactions_runtime.so:system/lib/libactions_runtime.so \
  vendor/actions/gs702a/proprietary/lib/avd_mkv.so:system/lib/avd_mkv.so \
  vendor/actions/gs702a/proprietary/lib/vd_mjpg.so:system/lib/vd_mjpg.so \
  vendor/actions/gs702a/proprietary/lib/apRMA.so:system/lib/apRMA.so \
  vendor/actions/gs702a/proprietary/lib/adACELP.so:system/lib/adACELP.so \
  vendor/actions/gs702a/proprietary/lib/vd_rvg2.so:system/lib/vd_rvg2.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Video.Decoder.so:system/lib/libOMX.Action.Video.Decoder.so \
  vendor/actions/gs702a/proprietary/lib/vd_flv1.so:system/lib/vd_flv1.so \
  vendor/actions/gs702a/proprietary/lib/adAMR.so:system/lib/adAMR.so \
  vendor/actions/gs702a/proprietary/lib/adAC3.so:system/lib/adAC3.so \
  vendor/actions/gs702a/proprietary/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
  vendor/actions/gs702a/proprietary/lib/adFLAC.so:system/lib/adFLAC.so \
  vendor/actions/gs702a/proprietary/lib/vd_h263.so:system/lib/vd_h263.so \
  vendor/actions/gs702a/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
  vendor/actions/gs702a/proprietary/lib/adOGG.so:system/lib/adOGG.so \
  vendor/actions/gs702a/proprietary/lib/avd_avi.so:system/lib/avd_avi.so \
  vendor/actions/gs702a/proprietary/lib/adWMASTD.so:system/lib/adWMASTD.so \
  vendor/actions/gs702a/proprietary/lib/avd_ts.so:system/lib/avd_ts.so \
  vendor/actions/gs702a/proprietary/lib/libACT_V4L2HAL.so:system/lib/libACT_V4L2HAL.so \
  vendor/actions/gs702a/proprietary/lib/vd_xvid.so:system/lib/vd_xvid.so \
  vendor/actions/gs702a/proprietary/lib/avd_rm.so:system/lib/avd_rm.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Image.Decoder.so:system/lib/libOMX.Action.Image.Decoder.so \
  vendor/actions/gs702a/proprietary/lib/libvinit.so:system/lib/libvinit.so \
  vendor/actions/gs702a/proprietary/lib/libGAL.so:system/lib/libGAL.so \
  vendor/actions/gs702a/proprietary/lib/adPCM.so:system/lib/adPCM.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Audio.Decoder.so:system/lib/libOMX.Action.Audio.Decoder.so \
  vendor/actions/gs702a/proprietary/lib/libperformance.so:system/lib/libperformance.so \
  vendor/actions/gs702a/proprietary/lib/libACT_FD.so:system/lib/libACT_FD.so \
  vendor/actions/gs702a/proprietary/lib/libACT_EncAPI.so:system/lib/libACT_EncAPI.so \
  vendor/actions/gs702a/proprietary/lib/apWMA.so:system/lib/apWMA.so \
  vendor/actions/gs702a/proprietary/lib/libGLSLC.so:system/lib/libGLSLC.so \
  vendor/actions/gs702a/proprietary/lib/apAMR.so:system/lib/apAMR.so \
  vendor/actions/gs702a/proprietary/lib/libOpenMAXAL.so:system/lib/libOpenMAXAL.so \
  vendor/actions/gs702a/proprietary/lib/adAAC.so:system/lib/adAAC.so \
  vendor/actions/gs702a/proprietary/lib/libalc.so:system/lib/libalc.so \
  vendor/actions/gs702a/proprietary/lib/vd_vc1.so:system/lib/vd_vc1.so \
  vendor/actions/gs702a/proprietary/lib/adAPE.so:system/lib/adAPE.so \
  vendor/actions/gs702a/proprietary/lib/libvde_core.so:system/lib/libvde_core.so \
  vendor/actions/gs702a/proprietary/lib/libdms.so:system/lib/libdms.so \
  vendor/actions/gs702a/proprietary/lib/adWMAPRO.so:system/lib/adWMAPRO.so \
  vendor/actions/gs702a/proprietary/lib/vd_h264.so:system/lib/vd_h264.so \
  vendor/actions/gs702a/proprietary/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
  vendor/actions/gs702a/proprietary/lib/libdmr.so:system/lib/libdmr.so \
  vendor/actions/gs702a/proprietary/lib/vd_rv34.so:system/lib/vd_rv34.so \
  vendor/actions/gs702a/proprietary/lib/adDTS.so:system/lib/adDTS.so \
  vendor/actions/gs702a/proprietary/lib/libbacklight.so:system/lib/libbacklight.so \
  vendor/actions/gs702a/proprietary/lib/libOMX.Action.Video.Camera.so:system/lib/libOMX.Action.Video.Camera.so \
  vendor/actions/gs702a/proprietary/lib/avd_mpg.so:system/lib/avd_mpg.so \
  vendor/actions/gs702a/proprietary/lib/libPopupVideo.so:system/lib/libPopupVideo.so \
  vendor/actions/gs702a/proprietary/lib/libctest.so:system/lib/libctest.so \
  vendor/actions/gs702a/proprietary/lib/libfacelock_jni.so:system/lib/libfacelock_jni.so \
  vendor/actions/gs702a/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
  vendor/actions/gs702a/proprietary/lib/apDTS.so:system/lib/apDTS.so \
  vendor/actions/gs702a/proprietary/lib/avd_flv.so:system/lib/avd_flv.so \
  vendor/actions/gs702a/proprietary/lib/vd_vp6.so:system/lib/vd_vp6.so \
  vendor/actions/gs702a/proprietary/lib/libACT_ISP.so:system/lib/libACT_ISP.so \
  vendor/actions/gs702a/proprietary/lib/libctrlpt.so:system/lib/libctrlpt.so \
  vendor/actions/gs702a/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
  vendor/actions/gs702a/proprietary/lib/apAPE.so:system/lib/apAPE.so \
  vendor/actions/gs702a/proprietary/lib/apFLAC.so:system/lib/apFLAC.so \
  vendor/actions/gs702a/proprietary/lib/adAWB.so:system/lib/adAWB.so \
  vendor/actions/gs702a/proprietary/lib/id_jpg.so:system/lib/id_jpg.so \
  vendor/actions/gs702a/proprietary/lib/libffmpeg_wrapper.so:system/lib/libffmpeg_wrapper.so \
  vendor/actions/gs702a/proprietary/lib/vd_mpeg.so:system/lib/vd_mpeg.so \
  vendor/actions/gs702a/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
  vendor/actions/gs702a/proprietary/lib/apAAC.so:system/lib/apAAC.so \
  vendor/actions/gs702a/proprietary/lib/avd_ogm.so:system/lib/avd_ogm.so \
  vendor/actions/gs702a/proprietary/lib/adWMALSL.so:system/lib/adWMALSL.so \
  vendor/actions/gs702a/proprietary/lib/libspeexresampler.so:system/lib/libspeexresampler.so \
  vendor/actions/gs702a/proprietary/lib/libactions-ril.so:system/lib/libactions-ril.so \
  vendor/actions/gs702a/proprietary/lib/hw/lights.ATM702X.so:system/lib/hw/lights.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/gpuhwcomposer.ATM702X.so:system/lib/hw/gpuhwcomposer.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/gralloc.ATM702X.so:system/lib/hw/gralloc.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
  vendor/actions/gs702a/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
  vendor/actions/gs702a/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
  vendor/actions/gs702a/proprietary/lib/hw/sensors.ATM702X.so:system/lib/hw/sensors.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
  vendor/actions/gs702a/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
  vendor/actions/gs702a/proprietary/lib/hw/lights.goldfish.so:system/lib/hw/lights.goldfish.so \
  vendor/actions/gs702a/proprietary/lib/hw/overlay.ATM702X.so:system/lib/hw/overlay.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \
  vendor/actions/gs702a/proprietary/lib/hw/displayengine.ATM702X.so:system/lib/hw/displayengine.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/camera.goldfish.so:system/lib/hw/camera.goldfish.so \
  vendor/actions/gs702a/proprietary/lib/hw/cvbs.ATM702X.so:system/lib/hw/cvbs.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/hwcomposer.ATM702X.so:system/lib/hw/hwcomposer.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
  vendor/actions/gs702a/proprietary/lib/hw/camera.ATM702X.so:system/lib/hw/camera.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
  vendor/actions/gs702a/proprietary/lib/hw/hdmi.ATM702X.so:system/lib/hw/hdmi.ATM702X.so \
  vendor/actions/gs702a/proprietary/lib/egl/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \
  vendor/actions/gs702a/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
  vendor/actions/gs702a/proprietary/lib/egl/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \
  vendor/actions/gs702a/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
  vendor/actions/gs702a/proprietary/lib/egl/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \
  vendor/actions/gs702a/proprietary/bin/pfmnceserver:system/bin/pfmnceserver \
  vendor/actions/gs702a/proprietary/bin/rild:system/bin/rild \
  vendor/actions/gs702a/proprietary/bin/dosfslabel:system/bin/dosfslabel \
  vendor/actions/gs702a/proprietary/framework/actions.jar:system/framework/actions.jar \
  vendor/actions/gs702a/proprietary/app/ActSensorCalib.apk:system/app/ActSensorCalib.apk \
  vendor/actions/gs702a/proprietary/xbin/iostat:system/xbin/iostat \
  vendor/actions/gs702a/proprietary/xbin/e2fsck:system/xbin/e2fsck \
  vendor/actions/gs702a/proprietary/xbin/usb_modeswitch:system/xbin/usb_modeswitch \
  vendor/actions/gs702a/proprietary/xbin/netserver:system/xbin/netserver \
  vendor/actions/gs702a/proprietary/xbin/mke2fs:system/xbin/mke2fs \
  vendor/actions/gs702a/proprietary/xbin/tcpdump:system/xbin/tcpdump \
  vendor/actions/gs702a/proprietary/xbin/netperf:system/xbin/netperf \
